### ISSUE TITLE
Run `azd provision` error on Windows

### ISSUE THREAD

**Issue by NanaXiong00** [pinecone-io/pinecone-assistant-azd#12]
**Describe the issue:**
When running `azd provision` on Windows, an error is displayed indicating a syntax rule error in the hook script as follows:
![image](https://github.com/user-attachments/assets/7e54e4fd-0598-40f8-87cb-f4578ce2cafe)

**Repro Steps:**
1. Clone the project.
2. Run `python -m venv .venv` and `.venv\Scripts\activate`.
3. Run `pip install -r requirements.txt`.
4. Run `azd auth login`.
5. Run `npm i`.
6. Run `npm run env:init`.
7. Run `azd provision`.

**Environment:**
- Azd version: azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)
- OS: Windows desktop.

**Expected behavior:**
Run `azd provision` successfully.

@hemarina and @cwaddingham for notification.

**Comment by NanaXiong00** [comment]
@cwaddingham The issue described above can still be reproduced according to the latest code test. A code review found that the problem is `preprovision.ps1` file  in the [code](https://github.com/pinecone-io/pinecone-assistant-azd/blob/main/.azd/hooks/preprovision.ps1#L6-L16) , where `bash` syntax was incorrectly used instead of `powershell` syntax.

**Comment by cwaddingham** [comment]
@NanaXiong00 please try it again.

**Comment by NanaXiong00** [comment]
> @NanaXiong00 please try it again.

@cwaddingham Based on the latest code retest, the following error occurred:
- Run command `npm run env:init`:
![Screenshot 2024-08-27 144116](https://github.com/user-attachments/assets/bd9e2f55-6687-4e68-9c97-606b552645b8)
- Run command `azd provision`:
![image](https://github.com/user-attachments/assets/354abe35-f393-41b6-9366-19f12a846ee9)

**Comment by cwaddingham** [comment]
@NanaXiong00 given the number of issues that have come up with running this template on Windows we're going to remove support for that OS from it. Going forward, it will be supported on MacOS and Linux. We may revisit this in the future, but for now, this first iteration will be POSIX-only.

**Comment by NanaXiong00** [comment]
@cwaddingham While testing the template on macOS according to the instructions in `README.md`, the following issues were encountered:
![Screenshot 2024-08-28 at 01 38 42](https://github.com/user-attachments/assets/645aeb7a-5046-4164-a6ab-059736847f25)
It is recommended to include dependency installation steps in the `README.md` to prevent these issues.
