### ISSUE TITLE
`azd provision` fails to retrieve environment name

### ISSUE THREAD

**Issue by NanaXiong00** [pinecone-io/pinecone-assistant-azd#13]
**Describe the issue:**
Unable to correctly retrieve the environment name using `azd provision`, as shown below:
![Screenshot 2024-08-23 154108](https://github.com/user-attachments/assets/a0d6adee-55cf-42ca-a970-c27d2369d89b)

**Repro Steps:**
1. Open in GitHub Codespaces.
2. Run `python -m venv .venv` and `source .venv/bin/activate`.
3. Run `pip install -r requirements.txt`.
4. Run `azd auth login`.
5. Run `npm i`.
6. Run `npm run env:init`.
7. Run `azd provision`.

**Environment:**
- Azd version: azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)
- OS: Codespaces, Dev Containers.

**Expected behavior:**
`azd provision` can correctly retrieve the environment name.

@hemarina and @cwaddingham for notification.

**Comment by vhvb1989** [comment]
Add a mapping for `environmentName` in parameters.json like

```
 "environmentName": {
      "value": "${AZURE_ENV_NAME}"
    },
```

Suggested PR: https://github.com/pinecone-io/pinecone-assistant-azd/pull/14
