### ISSUE TITLE
[Bug] No error reported when an incorrect Pinecone API key was supplied

### ISSUE THREAD

**Issue by puicchan** [pinecone-io/pinecone-assistant-azd#18]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I provided an incorrect Pinecone API key, as a result, the assistant "example-assistant" was not created in Pinecone console. No error was reported. It would be good to catch invalid API key in script so that customer knows how and what to rectify. 

### Expected Behavior

Script to set up environment should catch invalid API key and ask customer to provide the correct key.

### Steps To Reproduce

1. Create new Codespace
2. Follow steps in readme
3. Provide an invalid or partial key when prompted.
4. Run `azd provision` and `azd deploy` 

### Environment

```markdown
(Used Codespace)
```

**Comment by cwaddingham** [comment]
@puicchan good callout, I've added a try/except block to test for a valid API key in the latest PR.
