### ISSUE TITLE
Fail to run `npm i` in Codespaces and Dev Containers

### ISSUE THREAD

**Issue by NanaXiong00** [pinecone-io/pinecone-assistant-azd#4]
**Describe the issue:**
When running the `npm i` command according to [README.md](https://github.com/pinecone-io/pinecone-assistant-azd?tab=readme-ov-file#dependency-installation), the following error appears:
![image](https://github.com/user-attachments/assets/f93253ee-ae0b-440c-9fa7-e5cb94aa5347)

After installing `Node.js` using the command:
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
nvm install --lts
```
The dependency conflict problem is as follows;
![image](https://github.com/user-attachments/assets/e6c48dc2-b00e-4f0f-83a3-097944c001cd)

**Repro Steps:**

1. Open in GitHub Codespaces.
2. Run `python -m venv .venv` and `source .venv/bin/activate`.
3. Run `pip install -r requirements.txt`.
4. Run `azd auth login`.
5. Run `npm i`.

**Environment:**
- Azd version: azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)
- OS: Codespaces, Dev Containers

**Expected behavior:**
No need to manually install `Node.js` and run `npm i` successfully.

@hemarina and @cwaddingham  for notification.

**Comment by cwaddingham** [comment]
Resolved in branch "address-awesome-azd-issues".
