### ISSUE TITLE
Extra double quotes were generated in `.env.local`

### ISSUE THREAD

**Issue by NanaXiong00** [pinecone-io/pinecone-assistant-azd#5]
**Describe the issue:**
Running `npm run env:init` to generate the `.env.local` file resulted in an error, with the following details:
![image](https://github.com/user-attachments/assets/aed4acf6-db56-4c0d-98c4-78a3472e7dae)
![image](https://github.com/user-attachments/assets/0b5c4b6b-d5e5-472d-9ad7-d9f7cc800721)

**Repro Steps:**
1. Open in GitHub Codespaces.
2. Run `python -m venv .venv` and `source .venv/bin/activate`.
3. Run `pip install -r requirements.txt`.
4. Run `azd auth login`.
5. Run `npm i`.
6. Run `npm run env:init`.

**Environment:**
- Azd version: azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)
- OS: Codespaces, Dev Containers and Windows desktop.

**Expected behavior:**
Run `npm run env:init` successfully.

@hemarina and @cwaddingham  for notification.

**Comment by cwaddingham** [comment]
Resolved in branch "address-awesome-azd-issues".
