### ISSUE TITLE
Fail to run `python src/file_manager/upload.py`

### ISSUE THREAD

**Issue by NanaXiong00** [pinecone-io/pinecone-assistant-azd#7]
**Describe the issue:**
Running `python src/file_manager/upload.py` error in windows, as follows：
![image](https://github.com/user-attachments/assets/5fb02b07-378d-4361-bf1e-4a707ae1dc78)

**Repro Steps:**
1. Clone the project.
2. Run `python -m venv .venv` and `source .venv/bin/activate`.
3. Run `pip install -r requirements.txt`.
4. Run `azd auth login`.
5. Run `npm i`.
6. Run `npm run env:init`.
7. Run `python src/file_manager/upload.py`

**Environment:**
- Azd version: azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)
- OS: Windows desktop.

**Expected behavior:**
Run `python src/file_manager/upload.py` successfully.

@hemarina and @cwaddingham  for notification.

**Comment by cwaddingham** [comment]
Resolved in branch "address-awesome-azd-issues".
