### ISSUE TITLE
Clone the project command error in README

### ISSUE THREAD

**Issue by NanaXiong00** [pinecone-io/pinecone-assistant-azd#8]
**Describe the issue:**
Runing `azd init -t pinecone-assistant-azd` to clone the project according to [README.md](https://github.com/pinecone-io/pinecone-assistant-azd#want-to-move-fast), and the following error is displayed：
![image](https://github.com/user-attachments/assets/97c2e890-83a4-4cf7-a406-4d5ad65208ed)

**Suggestion:**
Update to `azd init -t pinecone-io/pinecone-assistant-azd` in README.

@hemarina and @cwaddingham  for notification.

**Comment by cwaddingham** [comment]
Resolved in branch "address-awesome-azd-issues".
